apiVersion: v1
kind: Pod
metadata:
  name: dummy-local-vol3
  namespace: rook-ceph-example
  labels:
    name: dummy-local-vol3
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'while true; do echo "[2]The local volume is mounted!" >> /mnt/vol3/dummy-vol3.txt && sleep 5; done']
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /mnt/
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: rook-ceph-example-pvc
