apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: keti-cephfs-pvc-01
        namespace: keti-cephfs
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 10Gi
        storageClassName: keti-cephfs-cr
