apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-request-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-request
  template:
    metadata:
      labels:
        app: python-request
    spec:
      containers:
      - name: python-request
        image: gwangyong/flask-ex:0.3
        env:
#        - name: TARGET_URL
#          value: "http://rook-ceph-rgw-keti-store.rook-ceph.svc:80"
        - name: AWS_ACCESS_KEY_ID
          value: "47QDB0XBGUZ5I9H8VL8U"
        - name: AWS_SECRET_ACCESS_KEY
          value: "dljjLsINa9DhqN5kWCkw6u4pTECaLgqqnZIAiO7X"
        - name: AWS_HOST
          value: "http://rook-ceph-rgw-keti-store.rook-ceph.svc:80"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-request-service
spec:
  selector:
    app: python-request
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
